environment: dev
stack_name: alvinator

core:
    region: ap-northeast-1

jenkins:
    enabled: False
    ami_id: ami-0db8a3e80938a5195
    instance_type: t2.medium

cloud_ide:
    enabled: True
    ami_id: ami-0ee5817af0936cba6
    instance_type: t2.medium
    iam_role_policies: [
        "service-role/AmazonEC2RoleforSSM",
        "PowerUserAccess"
    ]
    domain_name: "*.adelagon.com"
    
